services:

  your_life.data.user_service:
    class: YourLife\DataBundle\Service\UserService
    arguments:
      - @doctrine_mongodb
      - @security.encoder_factory
      - @your_life.data.user_level_service

  your_life.data.mission_service:
    class: YourLife\DataBundle\Service\MissionService
    arguments:
      - @doctrine_mongodb
      - %yourlife.data.mission_photos_path%

  your_life.data.mission_result_service:
    class: YourLife\DataBundle\Service\MissionResultService
    arguments:
      - @doctrine_mongodb
      - @your_life.data.user_service
      - %yourlife.data.mission_result_photos_path%

  your_life.data.user_level_service:
    class: YourLife\DataBundle\Service\UserLevelService