services:

  your_life.data.user_service:
    class: YourLife\DataBundle\Service\UserService
    arguments:
      - @doctrine_mongodb
      - @security.encoder_factory

  your_life.data.mission_service:
    class: YourLife\DataBundle\Service\MissionService
    arguments:
      - @doctrine_mongodb
      - %yourlife.data.mission_photos_path%