ylab_get_all_missions:
  pattern: /missions
  defaults: { _controller: YourLifeApiBundle:Missions:getList }
  requirements:
    _method: GET

ylab_get_one_mission:
  pattern: /missions/{id}
  defaults: { _controller: YourLifeApiBundle:Missions:get }
  requirements:
    _method: GET

ylab_update_mission:
  pattern: /missions/{id}
  defaults: { _controller: YourLifeApiBundle:Missions:update }
  requirements:
    _method: PUT

ylab_create_mission_reports:
  pattern: /missions/{id}/reports
  defaults: { _controller: YourLifeApiBundle:Missions:createReport }
  requirements:
    _method: POST

ylab_get_available_missions:
  pattern: /available_missions
  defaults: { _controller: YourLifeApiBundle:Missions:getAvailableMissions }
  requirements:
    _method: GET