ylab_get_all_reports:
  pattern: /reports
  defaults: { _controller: YourLifeApiBundle:Reports:getList }
  requirements:
    _method: GET

ylab_get_one_report:
  pattern: /reports/{id}
  defaults: { _controller: YourLifeApiBundle:Reports:get }
  requirements:
    _method: GET

ylab_create_report:
  pattern: /reports
  defaults: { _controller: YourLifeApiBundle:Reports:create }
  requirements:
    _method: POST