ylab_get_users:
  pattern: /users
  defaults: { _controller: YourLifeApiBundle:Users:getList }
  requirements:
    _method: GET

ylab_create_user:
  pattern: /users
  defaults: { _controller: YourLifeApiBundle:Users:create }
  requirements:
    _method: POST

ylab_get_user:
  pattern: /users/{id}
  defaults: { _controller: YourLifeApiBundle:Users:get }
  requirements:
    _method: GET