security:

    encoders:
        YourLife\DataBundle\Document\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        mongodb_provider:
            mongodb: { class: YourLife\DataBundle\Document\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        auth:
            pattern:  ^/auth/(login|register)$
            security: false

#        root:
#            pattern:  ^/$
#            security: false

        secured_area:
            pattern: ^/
            form_login:
                login_path: your_life_web_login
                check_path: your_life_web_login_check
            logout:
                path:   your_life_web_logout
                target: your_life_web_root
            #anonymous: ~

    access_control:
        - { path: ^/auth/register$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
