your_life_web_login:
    pattern: /login
    defaults: { _controller: YourLifeWebBundle:Auth:login }

your_life_web_login_check:
    pattern: /login_check

your_life_web_logout:
    pattern: /logout

your_life_web_register:
    pattern: /register
    defaults: { _controller: YourLifeWebBundle:Auth:register }
