your_life_web_mission_get_available:
    pattern: /available
    defaults: { _controller: YourLifeWebBundle:Mission:missionGetAvailable }

your_life_web_mission_get_active:
    pattern: /active
    defaults: { _controller: YourLifeWebBundle:Mission:missionGetActive }

your_life_web_mission_get_complete:
    pattern: /complete
    defaults: { _controller: YourLifeWebBundle:Mission:missionGetComplete }

your_life_web_mission_get_canceled:
    pattern: /canceled
    defaults: { _controller: YourLifeWebBundle:Mission:missionGetCanceled }

your_life_web_mission:
    pattern: /{id}
    defaults: { _controller: YourLifeWebBundle:Mission:mission }

