ylab_missions:
  resource: "@YourLifeApiBundle/Resources/config/routing/missions.yml"
  prefix: /

ylab_reports:
  resource: "@YourLifeApiBundle/Resources/config/routing/reports.yml"
  prefix: /

ylab_users:
  resource: "@YourLifeApiBundle/Resources/config/routing/users.yml"
  prefix: /

ylab_sessions:
  resource: "@YourLifeApiBundle/Resources/config/routing/sessions.yml"
  prefix: /